# Configuration of Hugo
# Guide: https://sourcethemes.com/academic/docs/get-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Jean-Michel Bruel"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://jmbruel.github.io/smartjmb/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `{year}`.
copyright = "&copy; 2020 - ACDC. Last update: 14/10/2020"

publishDir = "docs"

# Your details.
team = "SM@RT"
name = "Jean-Michel Bruel"
role = "Professor of Software Engineering"
office_hours = "http://doodle.com/jmbruel"
phone = "+33 (0)6.07.65.19.70"
twitter = "jmbruel"
skype = "jmbruel"
telegram = "jmbruel"


# Organizations/Affiliations.
#   Separate multiple entries with a comma, using the form: `[ {name="Org1", url=""}, {name="Org2", url=""} ]`.
organizations = [ 
  { name = "University of Toulouse", url = "http://www.univ-toulouse.fr/" },
  { name = "IRIT Laboratory", url = "http://www.irit.fr/" } 
  ]
# Publication types.
#   Used to categorize publications.
#   The index of the publication type in the list is used as its unique numerical identifier.
#   The numeric ID is used in a publication's frontmatter to categorize it.
#   The language can be edited below.
#   For multi-lingual sites, copy this block to each language section at the end of this file.
publication_types = [
  'Uncategorized',  # 0
  'Conference proceedings',  # 1
  'Journal',  # 2
  'Work in progress',  # 3
  'Technical report',  # 4
  'Book',  # 5
  'Book chapter'  # 6
]

############################
## Advanced options below ##
############################

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false
removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

summaryLength = 30  # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Workaround Hugo publishing taxonomy URLs as plurals - consistently use singular across Academic.
[permalinks]
  authors = "/author/:slug/"
  tags = "/tag/:slug/"
  categories = "/category/:slug/"
  publication_types = "/publication-type/:slug/"

[outputs]
  home = [ "HTML", "RSS" ]
  #section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

# Configure the Markdown renderer.
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 60.0

  [[related.indices]]
    name = "summary"
    weight = 50.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0

  [[related.indices]]
    name = "authors"
    weight = 20.0

# Install Wowchemy
[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic"

# Social/Academic Networking
#
# Icon pack "fa" includes the following social network icons:
#
#   twitter, weibo, linkedin, github, facebook, pinterest, google-plus,
#   youtube, instagram, soundcloud
#
#   For email icon, use "fa" icon pack, "envelope" icon, and
#   "mailto:your@email.com" as the link.
#
#   Full list: https://fortawesome.github.io/Font-Awesome/icons/
#
# Icon pack "ai" includes the following academic network icons:
#
#   google-scholar, arxiv, orcid, researchgate, mendeley
#
#   Full list: https://jpswalsh.github.io/academicons/

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:bruel@irit.fr"

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "//twitter.com/jmbruel"

[[params.social]]
  icon = "linkedin"
  icon_pack = "fa"
  link = "https://www.linkedin.com/in/jmbruel/"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "//github.com/jmbruel"

[[params.social]]
  icon = "researchgate"
  icon_pack = "ai"
  link = "https://www.researchgate.net/profile/Jean-Michel_Bruel2"

[[params.social]]
  icon = "facebook"
  icon_pack = "fa"
  link = "https://www.facebook.com/jmbruel"

[[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.fr/citations?user=5shVHyoAAAAJ&hl=en&oi=ao"

# Fixing warning
disableKinds = ["home"]
